### ISSUE TITLE
How does one compile this project?

### ISSUE THREAD

**Issue by Wheatwizard** [cheezgi/stones#4]
I'm sorry if this is obvious, I have little experience with rust but I haven't been able to compile this project.

I have done a `cargo build` in the top level directory but `rustc src/main.rs` still fails to find the crate for argparse?  Is there anything additional that needs to be done to build this project?

**Comment by cheezgi** [comment]
Rust is compiled, so `cargo build` emits a binary in the `target/build/debug` directory. You can use `cargo run` to run the binary through cargo, or `./target/debug/stones` to run it directly. Be aware that the hello world example is broken (and probably has been for a while). Have fun!
